#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Yuri Cherio

unset wait_lock # wait for the lock to become available before quitting or killing others
unset wait_term # run-this-one: keep sending SIGTERM for this long
unset wait_kill # run-this-one: keep sending SIGKILL for this long
unset run_anyway # run another instance after lock timeout no matter what
unset lock_token # command identifier token; defaults to command hash
unset lock_check # just test if another process holds the lock
unset fail_exit_code # custom error exit code
unset debug_file_path # Path to the debug file

while [ $# -gt 0 ] ; do
	case "$1" in
	-w) { shift; wait_lock="$1"; } ;; # wait for the lock to become available
	-t) { shift; wait_term="$1"; } ;; # TERM the other process instances after this secs
	-k) { shift; wait_kill="$1"; } ;; # KILL the other process instances after this secs
	-a) run_anyway="$1" ;;
	-i) { shift; lock_token="$1"; } ;; # command identifier token; defaults to command hash
	-T) lock_check="$1" ;; #
	-E) { shift; fail_exit_code="$1"; } ;; # Custom error exit code
	-D) { shift; debug_file_path="$1"; } ;; #
	-h|--help) exec man -P cat "${0##*/}" ;; # Display help
	'') ;; # Ignore empty arguments
	--) { shift; break; } ;; # The rest is the user supplied command line
	*) { break; } ;; # Beginning of the user supplied command line
	esac
	shift
done

_debug() {
	[ -n "$debug_file_path" ] && echo "$1" >> "$debug_file_path"
	[ -n "$2" ] && { [ "$2" != '0' ] && echo "$1" >&2; exit "$2"; }
}

[ $# -eq 0 ] && _debug "ERROR: no arguments specified" 1

: "${fail_exit_code:=122}" # When undefined, set the default

[ "${wait_lock##*[!0-9]}" = "$wait_lock" ] || _debug "Error: option -w requires an integer" 1
[ "${wait_term##*[!0-9]}" = "$wait_term" ] || _debug "Error: option -k requires an integer" 1
[ "${wait_kill##*[!0-9]}" = "$wait_kill" ] || _debug "Error: option -K requires an integer" 1
[ "${fail_exit_code##*[!0-9]}" = "$fail_exit_code" ] || _debug "Error: option -E requires an integer" 1

if [ "${0##*/}" = "run-this-one" ]; then
	# by default wait for 10 minutes while terminating other processes
	[ "${wait_term:-0}" -eq '0' ] && [ "${wait_kill:-0}" -eq '0' ] && wait_term="600"
fi

unset lock_file_dir # Lock file directory
unset uid # System user ID

# Make an attempt to prepare a given directory to store command hashes
try_global_dir() {
	_dir="$1" # Try this directory
	# With one system call read both the permissions and owner of the directory
	_dir_stat="$(find "$_dir" -maxdepth 0 -type d -printf '%m %U' 2>/dev/null)" # e.g. "755 bob"
	if [ -z "$_dir_stat" ]; then # the directory doesn't exist - try to create it
		if mkdir -m 700 "$_dir" 2>/dev/null; then
			lock_file_dir="$_dir"
		fi
	elif [ "${_dir_stat##* }" = "${uid:=$(id -u)}" ]; then # this is a DIR with the matching owner
		if [ "${_dir_stat%% *}" = "700" ] || chmod 700 "$_dir" 2>/dev/null; then # perm mask 700
			lock_file_dir="$_dir"
		fi
	fi
	[ -n "$lock_file_dir" ]
}

# Make an attempt to create a hash directory in XDG_RUNTIME_DIR
prog_name="one-run"
xdg_runtime_dir="${XDG_RUNTIME_DIR:-"/run/user/${uid:=$(id -u)}"}/$prog_name"
if [ -d "$xdg_runtime_dir" ] || mkdir -m 700 "$xdg_runtime_dir" 2>/dev/null; then
	lock_file_dir="$xdg_runtime_dir"
else
	# Make an attempt to create a hash directory in /dev/shm
	try_global_dir "/dev/shm/${prog_name}-${uid:=$(id -u)}" ||
		# Try creating it in /tmp; let's hope it's mounted as tmpfs
		try_global_dir "/tmp/${prog_name}-${uid}" ||
		# Sadly, this system doesn't see to be suitable - QUIT
		_debug "Failed to setup lock file" "$fail_exit_code"
fi

[ -n "$lock_file_dir" ] ||
	_debug "Failed to identify lock file directory" "$fail_exit_code"

# If custom command id token is not provided use command signature
lock_file_base="$(printf "%s" "${lock_token:-$*}" | sha256sum)}" # Hash the id token
lock_file_path="$lock_file_dir/${lock_file_base%% *}" # Ignore whitespace and what follows
_debug "Lock file: $lock_file_path"

_debug "[$$] Command: ${0##*/} $*"

find_lock_holders() {
	# Scanning /proc is orders of magnitude faster than using lsof or fuser
	find /proc -maxdepth 1 -name '[1-9]*' -uid "${uid:=$(id -u)}" -printf '%p/fd/9\n' 2>/dev/null |
		xargs stat -c '%N' 2>/dev/null |
		grep -oP "(?<=/proc/)\d+(?=/fd/\\d+\\Q' -> '$lock_file_path'\\E)" # | paste -sd " " -
}

if [ -n "$lock_check" ]; then
	lock_holder_pids="$(find_lock_holders)"
	[ -n "$lock_holder_pids" ] && echo $lock_holder_pids
	exec [ -z "$lock_holder_pids" ] # success when no one is holding the lock
fi

# Waits for the semaphore to acquire the lock and run user command
flock_and_exec() { # This function only returns if lock was unsuccessful
	_fwait_lock="$1"; shift # Wait time to acquire the lock, can be 0
	{ # Acquire the lock and run the user command
		if flock -x -w "$_fwait_lock" -E "$fail_exit_code" 9; then # We successfully acquired the lock
			_debug "Lock acquired, running command: $*"
			exec "$@" # Execute the user command
		fi
	} 9>"$lock_file_path"
}

flock_and_exec 0 "$@" # just try it

if [ "${wait_lock:-0}" -gt 0 ]; then
	ts_end="$(date -d "+$wait_lock sec" +%s)"
	wait_left_secs="$wait_lock"
	while [ "$wait_left_secs" -gt 0 ]; do
		flock_and_exec "$wait_left_secs" "$@" # this does not return if lock is successful
		wait_left_secs="$((ts_end - $(date +%s)))"
	done
fi

send_signal() {
	sig="$1"; shift

	lock_holder_pids="$(find_lock_holders)"
	[ -z "$lock_holder_pids" ] && return 1

	_debug "Sending signal $sig to $lock_holder_pids"
	kill -s "$sig" $lock_holder_pids # return success if at least one terminated
}

unset ts_issue1_quit # quit when no one holds the lock, but it can't be acquired

signal_lock_and_run() {
	duration="$1"; shift
	sig="$1"; shift

	ts_end="$(date -d "+$duration sec" +%s)"
	pause_secs="0"
	while :; do
		flock_and_exec "$pause_secs" "$@" # this does not return if lock is successful

		ts_now="$(date +%s)"
		wait_left_secs="$((ts_end - ts_now))"
		[ "$wait_left_secs" -le 0 ] && break
		pause_secs="$((pause_secs + 1))"
		[ "$pause_secs" -gt 15 ] && pause_secs="15"
		[ "$pause_secs" -gt "$wait_left_secs" ] && pause_secs="$wait_left_secs"


		if send_signal "$sig" ; then
			unset ts_issue1_quit
		else # there are not any processes holding the lock
			if [ -z "$ts_issue1_quit" ]; then
				ts_issue1_quit="$(date -d "+300 sec" +%s)" # bail in 5 min
				pause_secs=1 # reduce pause to 1 second
				_debug "Abnormality: no other process seems to be holding the lock and yet the lock could not be acquired" # ¯\_(ツ)_/¯
			elif [ "$ts_issue1_quit" -gt "$(date +%s)" ]; then
				_debug "Abnormality persists, giving up" 1
			fi
		fi
	done

	_debug "Expired $duration sec for signal $sig"
}

if [ "${wait_term:-0}" -gt 0 ]; then
	signal_lock_and_run "$wait_term" "TERM" "$@"
fi

if [ "${wait_kill:-0}" -gt 0 ]; then
	signal_lock_and_run "$wait_kill" "KILL" "$@"
fi

if [ -n "$run_anyway" ]; then
	_debug "Running anyway, replacing the lock file"
	rm -f "$lock_file_path"; # remove the lock file
	flock_and_exec 0 "$@"
	_debug "Still can not acquire the lock" "$fail_exit_code"
fi

exit "$fail_exit_code"
