#!/bin/sh
# Two processes take turns, waiting roughly two seconds, then sleeping for two seconds

export PATH="$(realpath "$(dirname "$0")/.."):$PATH"

cmd1() {
	token_id="$1"
	while true; do
		wait_lock="2"
		wait_term="2"
		wait_kill="2"
		sleep="7"
		ts="$(date +'%T.%N')"
		echo "${ts%??????} wait_lock=$wait_lock, wait_term=$wait_term, wait_kill=$wait_kill, sleep=$sleep"
		run-one -w "$wait_lock" -t "$wait_term" -k "$wait_kill" -i "$token_id" -D /dev/stdout -- \
			sh -c "trap '' TERM; echo 'GOT IT!'; sleep $sleep;"
		# echo "[$$] finished"
	done
	exit 0
}

if [ $# -eq 0 ]; then
	token_id="$(uuidgen)"
	tmux new-session -d -s "one-run-$$" "sleep 2; $0 $token_id" \; split-window -v "$0 $token_id" \; attach
	exit 0
fi

cmd1 "$@"
